TEMP: Initial work
AVSLab/bsk_rl pull request #214
Opened 2024-11-25 22:27 UTC by Mark2000

## Description
Closes #XXX

*Please include a summary, motivation, and context of the changes and the related issue.*

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### How should this pull request be reviewed?
- [ ] By commit
- [ ] All changes at once

## How Has This Been Tested?

*Please describe how tests have been updated to verify your changes.*

## Future Work

*What future tasks are needed, if any?*

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and release notes
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I changed an example ipynb, I have locally rebuilt the documentation

2025-02-09 01:36 UTC, dhutererprats commented on src/bsk_rl/utils/orbital.py
What is this random unit vector used for/

2025-02-09 01:38 UTC, dhutererprats commented on src/bsk_rl/act/continuous_action.py
What does the hardcoded '5700.0' specify here?

2025-02-09 01:49 UTC, dhutererprats commented on src/bsk_rl/sim/fsw.py
> +                f"Maneuver exceeds available Delta V ({np.linalg.norm(dv_N)}/{self.fuel_remaining} m/s)."
Doesn't this give you the percentage (above 100%) that the current requested dv maneuver exceeds the available amount by?  This division shouldn't give m/s unless I am missing something.

2025-02-09 01:53 UTC, dhutererprats commented on src/bsk_rl/sim/fsw.py
> +        self._dv_available -= np.linalg.norm(dv_N)
if np.linalg.norm(dv_N) > self.dv_available then it would not be subtracted from the _dv_available since it is not a valid/possible maneuver. I think if np.linalg.norm(dv_N) > self.dv_available then we need to pass and step out of the action_magic_thrust function right?

2025-02-09 02:08 UTC, dhutererprats requested changes
I have left comments on some of the commits just to clarify... I don't thing they are necessarily things you need to change except in the location where it is checked if np.linalg.norm(dv_N) > self.dv_available and even if that is the case we reduce the amount of _dv_available. We should fire the maneuver if it exceeds are dv capability so we would not reduce future dv_availability. 

Also I saw that the build gives some issues (like the python 3.11 or 3.10) but they dont seem to be relevant issues right.

2025-02-10 17:00 UTC, Mark2000 commented on src/bsk_rl/act/continuous_action.py
Opened a new issue to track this, since we use hardcoded 5700 as a normalization factor (approx. 1 orbit) in various places. https://github.com/AVSLab/bsk_rl/issues/225

2025-02-10 17:01 UTC, Mark2000 commented on src/bsk_rl/sim/fsw.py
> +                f"Maneuver exceeds available Delta V ({np.linalg.norm(dv_N)}/{self.fuel_remaining} m/s)."
The print statement results in something like `Maneuver exceeds available Delta V (3.5/1.2 m/s).`

2025-02-10 17:08 UTC, Mark2000 commented on src/bsk_rl/sim/fsw.py
> +        self._dv_available -= np.linalg.norm(dv_N)
Yeah, definitely should handle this more gracefully. Could just perform a `dv_available` sized thrust.

2025-04-30 14:27 UTC, Mark2000 commented on src/bsk_rl/data/composition.py
> +        return any(rewarder.is_terminated(satellite) for rewarder in self.rewarders)
Add these

2025-05-07 16:44 UTC, Mark2000 commented on src/bsk_rl/utils/wrappers.py
Not useful so not merging

2025-05-07 21:40 UTC, Mark2000 commented
Final PR commit plan:
- relative motion fsw, scene, data
- vizard support
- example script

2025-05-15 16:18 UTC, Mark2000 commented
Requires bsk commit first

2025-06-17 15:45 UTC, closed without merging

2025-06-17 15:45 UTC, Mark2000 commented
Actually implemented in #274